version: "3.7"

services:
  database_tripquote:
    image: postgres
    container_name: database_tripquote
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=tripquotedb
    volumes:
      - pgdata:/data/postgres
    network_mode: host
  app:
    build: .
    container_name: tripquoteapi
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
    network_mode: host

volumes:
  pgdata:
    driver: local
